# Generated by Django 3.1.3 on 2020-12-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('man', 'ERKEK'), ('women', 'KADIN'), ('unisex', 'UNISEX')], default='unisex', max_length=6),
        ),
    ]
