# Generated by Django 3.1.3 on 2020-12-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
