# Generated by Django 3.1.3 on 2020-12-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20201210_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='session_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
